"""Tests for CLI-backend process handling, timeouts, and provenance.

Three defects found while generating PTE chapter 1 through the agent CLIs:

- A timed-out CLI call reaped only the process we spawned. The agent's node
  grandchild survived, reparented to init, and kept consuming the subscription
  (one orphan was still alive 17 minutes later).
- The flat 180s per-call timeout was inherited from the hosted-API backend, but
  a real CLI chapter call runs several minutes, so every one was killed
  mid-flight and then burned its retries.
- Provenance always recorded --nvidia-model, so chapters generated by Claude or
  Codex were stamped with the Mistral model name.
"""

import argparse
import os
import signal
import subprocess
import sys
import time

import pytest

import generate_book_learning_materials as book


def make_args(**overrides):
    defaults = {
        "nvidia_model": "mistral-test",
        "backend": "nvidia",
        "claude_model": "sonnet",
        "codex_model": "gpt-5.5",
        "codex_reasoning_effort": "high",
        "model_timeout_seconds": None,
        "model_max_tokens": 8000,
        "model_max_retries": 0,
    }
    defaults.update(overrides)
    return argparse.Namespace(**defaults)


# --------------------------------------------------------------------------- #
# Process-group termination on timeout
# --------------------------------------------------------------------------- #

def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def test_timeout_kills_the_whole_process_group_not_just_the_child():
    # Parent spawns a grandchild that would outlive it, then both sleep. This is
    # the shape of the agent CLIs: a thin wrapper around a long-lived node child.
    script = (
        "import subprocess, sys, time;"
        "g = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(120)']);"
        "print(g.pid, flush=True);"
        "time.sleep(120)"
    )
    cmd = [sys.executable, "-c", script]

    # Capture the grandchild pid by running once without a timeout kill.
    probe = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, text=True, start_new_session=True
    )
    grandchild_pid = int(probe.stdout.readline().strip())
    assert _pid_alive(grandchild_pid)

    book.terminate_process_group(probe)

    deadline = time.time() + 10
    while time.time() < deadline and _pid_alive(grandchild_pid):
        time.sleep(0.1)

    assert not _pid_alive(grandchild_pid), (
        "grandchild survived termination and would be orphaned onto init"
    )


def test_run_cli_capture_raises_timeout_and_leaves_nothing_running():
    script = (
        "import subprocess, sys, time;"
        "subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(60)']);"
        "time.sleep(60)"
    )
    with pytest.raises(subprocess.TimeoutExpired):
        book.run_cli_capture(
            [sys.executable, "-c", script], input_text="", timeout_seconds=1
        )


def test_run_cli_capture_returns_streams_and_returncode():
    code = "import sys; sys.stdout.write(sys.stdin.read().upper()); sys.exit(3)"
    returncode, stdout, stderr = book.run_cli_capture(
        [sys.executable, "-c", code], input_text="hello", timeout_seconds=30
    )

    assert returncode == 3
    assert stdout == "HELLO"
    assert stderr == ""


def test_run_cli_capture_propagates_missing_binary():
    with pytest.raises(FileNotFoundError):
        book.run_cli_capture(
            ["definitely-not-a-real-binary-xyz"], input_text="", timeout_seconds=5
        )


# --------------------------------------------------------------------------- #
# Backend-aware timeout defaults
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("backend", ["claude-cli", "codex-cli"])
def test_cli_backends_default_to_the_long_timeout(backend):
    assert (
        book.resolve_model_timeout_seconds(make_args(backend=backend))
        == book.DEFAULT_CLI_TIMEOUT_SECONDS
    )


def test_nvidia_backend_keeps_the_short_api_timeout():
    assert (
        book.resolve_model_timeout_seconds(make_args(backend="nvidia"))
        == book.DEFAULT_API_TIMEOUT_SECONDS
    )


def test_cli_default_timeout_is_long_enough_for_a_real_chapter():
    # Measured full-chapter CLI calls ran 190-350s, with one over 600s.
    assert book.DEFAULT_CLI_TIMEOUT_SECONDS >= 600


@pytest.mark.parametrize("backend", ["nvidia", "claude-cli", "codex-cli"])
def test_explicit_timeout_always_wins(backend):
    args = make_args(backend=backend, model_timeout_seconds=42)
    assert book.resolve_model_timeout_seconds(args) == 42


def test_resolved_timeout_reaches_the_cli_backend(monkeypatch):
    seen = {}

    def fake_claude(prompt, *, model, timeout_seconds):
        seen["timeout"] = timeout_seconds
        return "ok"

    monkeypatch.setattr(book, "complete_via_claude_cli", fake_claude)
    fn = book.resolve_complete_fn(make_args(backend="claude-cli"), None, direct=True)
    fn("PROMPT")

    assert seen["timeout"] == book.DEFAULT_CLI_TIMEOUT_SECONDS


# --------------------------------------------------------------------------- #
# Backend / model provenance
# --------------------------------------------------------------------------- #

def test_provenance_records_the_model_that_actually_generated():
    assert book.active_model_name(make_args(backend="nvidia")) == "mistral-test"
    assert book.active_model_name(make_args(backend="claude-cli")) == "sonnet"
    assert book.active_model_name(make_args(backend="codex-cli")) == "gpt-5.5"


def test_provenance_does_not_stamp_cli_output_with_the_nvidia_model():
    # The exact defect: a Codex-generated chapter claimed it came from Mistral.
    codex = make_args(backend="codex-cli", codex_model="gpt-5.5")
    assert book.active_model_name(codex) != codex.nvidia_model


def test_active_backend_reported():
    assert book.active_backend(make_args(backend="codex-cli")) == "codex-cli"
    assert book.active_backend(make_args(backend="nvidia")) == "nvidia"
